"""Initial migration

Revision ID: 62481cb88ee6
Revises: 
Create Date: 2025-05-07 23:07:42.175670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62481cb88ee6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_specialization_id_fkey', 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'specialization', ['specialization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('exam_group_id_fkey', 'exam', type_='foreignkey')
    op.drop_constraint('exam_subject_id_fkey', 'exam', type_='foreignkey')
    op.drop_constraint('exam_room_id_fkey', 'exam', type_='foreignkey')
    op.drop_constraint('exam_teacher_id_fkey', 'exam', type_='foreignkey')
    op.create_foreign_key(None, 'exam', 'room', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exam', 'student_group', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exam', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exam', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('schedule_log_user_id_fkey', 'schedule_log', type_='foreignkey')
    op.drop_constraint('schedule_log_direction_id_fkey', 'schedule_log', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_log', 'direction', ['direction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedule_log', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('schedule_settings_direction_id_fkey', 'schedule_settings', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_settings', 'direction', ['direction_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('specialization_direction_id_fkey', 'specialization', type_='foreignkey')
    op.create_foreign_key(None, 'specialization', 'direction', ['direction_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('student_group_course_id_fkey', 'student_group', type_='foreignkey')
    op.create_foreign_key(None, 'student_group', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('subject_course_id_fkey', 'subject', type_='foreignkey')
    op.create_foreign_key(None, 'subject', 'course', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('teacher_subject_teacher_id_fkey', 'teacher_subject', type_='foreignkey')
    op.drop_constraint('teacher_subject_subject_id_fkey', 'teacher_subject', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_subject', 'teacher', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_subject', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_subject', type_='foreignkey')
    op.drop_constraint(None, 'teacher_subject', type_='foreignkey')
    op.create_foreign_key('teacher_subject_subject_id_fkey', 'teacher_subject', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key('teacher_subject_teacher_id_fkey', 'teacher_subject', 'teacher', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.create_foreign_key('subject_course_id_fkey', 'subject', 'course', ['course_id'], ['id'])
    op.drop_constraint(None, 'student_group', type_='foreignkey')
    op.create_foreign_key('student_group_course_id_fkey', 'student_group', 'course', ['course_id'], ['id'])
    op.drop_constraint(None, 'specialization', type_='foreignkey')
    op.create_foreign_key('specialization_direction_id_fkey', 'specialization', 'direction', ['direction_id'], ['id'])
    op.drop_constraint(None, 'schedule_settings', type_='foreignkey')
    op.create_foreign_key('schedule_settings_direction_id_fkey', 'schedule_settings', 'direction', ['direction_id'], ['id'])
    op.drop_constraint(None, 'schedule_log', type_='foreignkey')
    op.drop_constraint(None, 'schedule_log', type_='foreignkey')
    op.create_foreign_key('schedule_log_direction_id_fkey', 'schedule_log', 'direction', ['direction_id'], ['id'])
    op.create_foreign_key('schedule_log_user_id_fkey', 'schedule_log', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.create_foreign_key('exam_teacher_id_fkey', 'exam', 'teacher', ['teacher_id'], ['id'])
    op.create_foreign_key('exam_room_id_fkey', 'exam', 'room', ['room_id'], ['id'])
    op.create_foreign_key('exam_subject_id_fkey', 'exam', 'subject', ['subject_id'], ['id'])
    op.create_foreign_key('exam_group_id_fkey', 'exam', 'student_group', ['group_id'], ['id'])
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.create_foreign_key('course_specialization_id_fkey', 'course', 'specialization', ['specialization_id'], ['id'])
    # ### end Alembic commands ###
